#!/bin/bash

UGLIFY_COMMAND="uglifyjs -e  --compress --mangle --toplevel --beautify beautify=false,quote_style=3"

if [ "$1" = "help" ]; then
  echo "$0 [(staged|expanded|freq|wc|help)]"
elif [ "$1" = "staged" ]; then
  $UGLIFY_COMMAND -- <(git show :life.js)
elif [ "$1" = "expanded" ]; then
  uglifyjs --beautify quote_style=3 -- <($UGLIFY_COMMAND -- life.js)
elif [ "$1" = "freq" ]; then
  $UGLIFY_COMMAND -- life.js | sed -e "s/[^a-zA-Z]/ /g"  -e "s/  */ /g" | tr " " "\n" | dtk uc
elif [ "$1" = "wc" ]; then
  $UGLIFY_COMMAND -- life.js | wc
else
  $UGLIFY_COMMAND -- life.js
fi